# Generated by Django 4.0.4 on 2022-05-19 15:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0004_remove_cycleslength_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_cycle', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(35.0), django.core.validators.MaxValueValidator(41.0)])),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycles.cycleslength')),
            ],
        ),
    ]
